In [1]:
# From Python
# It requires OpenCV installed for Python
import sys
import cv2
import os
dir_path = r'D:\Projects\anomaly\openpose_full\openpose\build'
sys.path.append(dir_path + r'\python\openpose\Release')
os.environ['PATH']  = os.environ['PATH'] + ';' + dir_path + r'\x64\Release;' +  dir_path + r'\bin;'
model_path = r'D:\Projects\anomaly\openpose_full\openpose\models'
import pyopenpose as op
import numpy as np

# try:
#    
params = dict()
params["model_folder"] = model_path
params["number_people_max"] = 1
params["model_pose"] = "COCO"
params["scale_number"] = 3
# params["net_resolution"] = "320x176"
# params["face"] = False
# params["hand"] = False




In [2]:


adl_path='./data/urfall/images/adl/'
fall_path='./data/urfall/images/fall/'

adl_subdirs=[os.path.join(adl_path,f) for f in os.listdir(adl_path) if os.path.isdir(os.path.join(adl_path,f))]
fall_subdirs=[os.path.join(fall_path,f) for f in os.listdir(fall_path) if os.path.isdir(os.path.join(fall_path,f))]

# read one image to get the width and height
images=[f for f in os.listdir(adl_subdirs[0]) if f.endswith('.png')]
imge=os.path.join(adl_subdirs[0],images[0])
print(imge)
imageToProcess = cv2.imread(imge)
height,width,_=imageToProcess.shape
print(height,width)

#     # Starting OpenPose
opWrapper = op.WrapperPython()
opWrapper.configure(params)
opWrapper.start()
datum = op.Datum()

#     # Process Image

def get_keypoints(datum, imgedir):
    print(imgedir)
    
    images=[f for f in os.listdir(imgedir) if f.endswith('.png')]

    data_list=[]

    for imge in images:
        imge=os.path.join(imgedir,imge)
        # print(imge)

        imageToProcess = cv2.imread(imge)
        # resize image
        datum.cvInputData = imageToProcess
        opWrapper.emplaceAndPop(op.VectorDatum([datum]))
#         (1, 18, 3)
# Body keypoints: 
# [[[280.2432     208.87415      0.64724237]
#   [282.9698     230.89659      0.6435216 ]
#   [255.5746     230.88397      0.664216  ]
#   [239.08392    263.74384      0.5468522 ]
#   [236.3743     288.45322      0.5411244 ]
#   [310.43988    230.91676      0.63189036]
#   [321.36417    266.4916       0.55638134]
#   [318.6558     280.2273       0.53723913]
#   [269.212      291.23553      0.6013629 ]
#   [252.80048    299.47287      0.53248006]
#   [261.06946    362.4771       0.54206765]
#   [299.40912    291.24612      0.5939399 ]
#   [313.17737    299.4411       0.51269567]
#   [315.83344    362.4936       0.6140277 ]
#   [274.79318    203.43472      0.6479778 ]
#   [288.3995     203.44662      0.65742636]
#   [271.91708    206.19229      0.4327887 ]
#   [294.02472    206.23013      0.61766475]]]

        if datum.poseKeypoints is None:
            continue
        # normalize to width and height
        datum.poseKeypoints[:,:,0]=datum.poseKeypoints[:,:,0]/width-0.5
        datum.poseKeypoints[:,:,1]=datum.poseKeypoints[:,:,1]/height-0.5
        
        data_list.append(datum.poseKeypoints)
        # Display Image
        # print("Body keypoints: \n" + str(datum.poseKeypoints))

    #     cv2.imshow("OpenPose 1.7.0 - Tutorial Python API", datum.cvOutputData)
    #     if cv2.waitKey(1000//200) & 0xFF == ord('q'):
    #         break
    # cv2.destroyAllWindows()
# except Exception as e:
#     print(e)
#     sys.exit(-1)
    data_list=np.array(data_list)
    print ('data_list shape: ', data_list.shape)#data_list shape:  (138, 1, 18, 3)

    padding=np.zeros((300-data_list.shape[0],1,18,3))
    data_list=np.concatenate((data_list,padding),axis=0)
    data_list=data_list.reshape(300,18,3)

    return data_list

adl_data_list=[]

for adl_subdir in adl_subdirs:
    data_list=get_keypoints(datum, adl_subdir)
    adl_data_list.append(data_list)
    # break 

fall_data_list=[]
for fall_subdir in fall_subdirs:
    data_list=get_keypoints(datum, fall_subdir)
    fall_data_list.append(data_list)
    # break

# save data
adl_data_list=np.array(adl_data_list)
fall_data_list=np.array(fall_data_list)

np.save('./data/urfall/jointNumpy/adl_Data1124.npy',adl_data_list)
np.save('./data/urfall/jointNumpy/fall_Data1124.npy',fall_data_list)







./data/urfall/images/adl/adl-01-cam0-rgb\adl-01-cam0-rgb-001.png
480 640
./data/urfall/images/adl/adl-01-cam0-rgb
data_list shape:  (143, 1, 18, 3)
./data/urfall/images/adl/adl-02-cam0-rgb
data_list shape:  (149, 1, 18, 3)
./data/urfall/images/adl/adl-03-cam0-rgb
data_list shape:  (180, 1, 18, 3)
./data/urfall/images/adl/adl-04-cam0-rgb
data_list shape:  (150, 1, 18, 3)
./data/urfall/images/adl/adl-05-cam0-rgb
data_list shape:  (180, 1, 18, 3)
./data/urfall/images/adl/adl-06-cam0-rgb
data_list shape:  (218, 1, 18, 3)
./data/urfall/images/adl/adl-07-cam0-rgb
data_list shape:  (180, 1, 18, 3)
./data/urfall/images/adl/adl-08-cam0-rgb
data_list shape:  (172, 1, 18, 3)
./data/urfall/images/adl/adl-09-cam0-rgb
data_list shape:  (150, 1, 18, 3)
./data/urfall/images/adl/adl-10-cam0-rgb
data_list shape:  (300, 1, 18, 3)
./data/urfall/images/adl/adl-11-cam0-rgb
data_list shape:  (292, 1, 18, 3)
./data/urfall/images/adl/adl-12-cam0-rgb
data_list shape:  (233, 1, 18, 3)
./data/urfall/images/adl/ad